# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: $(Date:YYYY-MM-DD)$(Rev:.rr)_$(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)

# 1:  $(Date:MMddyy)$(Rev:.rr)_$(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)
# 2: 

trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      node_10_x:
        node_version: 10.x
  steps:
  # - task: NodeTool@0
  #   inputs:
  #     versionSpec: $(node_version)
  #   displayName: 'Install Node.js'

  # - task: Npm@1
  #   displayName: 'Npm install'
  #   inputs:
  #     command: 'install'

  - script: |
      GIT_SHORTSHA=`git rev-parse --short $(Build.SourceVersion)`
      echo "Git short sha: ${GIT_SHORTSHA}"
      echo "##vso[task.setvariable variable=short_sha]${GIT_SHORTSHA}"

  - script: echo $(short_sha)

  - script: echo $(Build.BuildNumber)